module.exports.baseURL = `https://poe.ninja/api/data/`
module.exports.standardLeague = `&league=Standard`
module.exports.currency = `currencyoverview?&type=Currency`
module.exports.divCard = `itemoverview?type=DivinationCard`
module.exports.essence = `itemoverview?type=Essence`
module.exports.fragment = `currencyoverview?type=Fragment`
module.exports.prophecy = `itemoverview?type=Prophecy`
module.exports.uniqueAccessory = `itemoverview?type=UniqueAccessory`
module.exports.uniqueArmour = `itemoverview?type=UniqueArmour`
module.exports.uniqueFlask = `itemoverview?type=UniqueFlask`
module.exports.uniqueJewel = `itemoverview?type=UniqueJewel`
module.exports.uniqueMap = `itemoverview?type=UniqueMap`
module.exports.uniqueWeapon = `itemoverview?type=UniqueWeapon`
module.exports.maps = `itemoverview?type=Map`
module.exports.resonator = `itemoverview?type=Resonator`
module.exports.fossil = `itemoverview?type=Fossil`
module.exports.scarab = `itemoverview?type=Scarab`
module.exports.incubator = `itemoverview?type=Incubator`
module.exports.oil = `itemoverview?type=Oil`
